# Generated by Django 4.1.6 on 2023-02-25 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_num', models.CharField(help_text='Enter the asset number', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.PositiveIntegerField(help_text='Enter the employees ID number', unique=True)),
                ('first_name', models.CharField(help_text="Enter in the associate's first name", max_length=30)),
                ('last_name', models.CharField(blank=True, help_text="Enter in the associate's last name", max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a work department', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('i', 'In-Process'), ('c', 'Completed'), ('d', 'Deferred')], default='i', help_text='Enter a status for CIP', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='cipIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_date', models.DateField(auto_now_add=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(help_text='Enter the summary of the CIP idea')),
                ('annual_savings', models.DecimalField(decimal_places=2, max_digits=8)),
                ('assets', models.ForeignKey(help_text='Enter the asset related to the CIP Idea', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.asset')),
                ('eng_support', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supporter', to='catalog.associate')),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originator', to='catalog.associate')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.status')),
            ],
        ),
        migrations.AddField(
            model_name='associate',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.dept'),
        ),
        migrations.AddField(
            model_name='asset',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.dept'),
        ),
    ]
