# Generated by Django 4.1.4 on 2023-02-21 18:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_num', models.CharField(help_text='Enter the asset number', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.PositiveIntegerField(help_text='Enter the employees ID number')),
                ('name', models.CharField(help_text="Enter in the associate's name", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cipClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a classification for the CIP', max_length=100)),
                ('code', models.CharField(help_text='Enter the code for the classification (e.g. S for Safety)', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a work department', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a work shift (e.g. 1st Shift)', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a status for the CIP (e.g. In-Process)', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cipIdea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular CIP entry', primary_key=True, serialize=False)),
                ('entered_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('annual_savings', models.DecimalField(decimal_places=2, max_digits=8)),
                ('assets', models.ManyToManyField(to='catalog.asset')),
                ('cip_class', models.ManyToManyField(to='catalog.cipclassification')),
                ('eng_support', models.ManyToManyField(help_text='Enter associate supporting CIP', related_name='supporter', to='catalog.associate')),
                ('originator', models.ManyToManyField(help_text='Enter associated that created the CIP Idea', related_name='originator', to='catalog.associate')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.status')),
            ],
        ),
        migrations.AddField(
            model_name='associate',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.dept'),
        ),
        migrations.AddField(
            model_name='associate',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.shift'),
        ),
        migrations.AddField(
            model_name='asset',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.dept'),
        ),
    ]
