# Generated by Django 4.1.4 on 2023-02-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cipidea',
            name='summary',
            field=models.TextField(help_text='Enter the summary of the CIP idea'),
        ),
    ]
