# Generated by Django 4.1.6 on 2023-02-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipidea',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
