# Generated by Django 4.1.6 on 2023-02-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associate',
            options={'ordering': ['name', 'dept', 'shift']},
        ),
    ]
