# Generated by Django 4.1.4 on 2023-02-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_cipidea_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='emp_id',
            field=models.PositiveIntegerField(help_text='Enter the employees ID number', unique=True),
        ),
    ]
